import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/svg+xml" href="/nafster_logo.svg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Image src="/nafster_logo.svg" alt="Nafster Logo" width={100} height={100} /> Nafster
        </h1>

        <p className={styles.description}>
          NFT sharing community
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>coming soon</h2>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
